import Image from "next/image";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Testimonials grid section</title>
        <link rel="icon" href="/favicon-32x32.png"  />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container  w-screen h-screen  mx-auto mt-20 sm:mt-52 px-5  ">
        <div className="  flex-row mb-10">
          <div className="flex flex-col sm:flex-row gap-10 sm:gap-2 ">
            <div className="basis-5/6  ">
              <div className="flex flex-col sm:flex-row gap-10 sm:gap-2 ">
                <div className="basis-[70%] bg-violet-700 p-5 rounded-lg drop-shadow-xl">
                  <div className=" flex gap-2 flex-row items-center">
                    <Image
                      className="rounded-full"
                      src="/image-daniel.jpg"
                      alt="img"
                      width={30}
                      height={30}
                    />

                    <div className="flex-col text-white ">
                      <h1 className="text-sm">Daniel Clifford</h1>
                      <p className="text-xs opacity-[50%]">Verified Graduate</p>
                    </div>
                  </div>
                  <div className="flex mt-2">
                    <h1 className="text-2xl font-bold text-white opacity-[80%]">
                      I received a job offer mid-course, and the subjects I
                      learned were current, if not more so, in the company I
                      joined. I honestly feel I got every penny’s worth.
                    </h1>
                  </div>
                  <div className="flex mt-2">
                    <h1 className="text-[13px] text-gray-300 opacity-[80%]">
                      “ I was an EMT for many years before I joined the
                      bootcamp. I’ve been looking to make a transition and have
                      heard some people who had an amazing experience here. I
                      signed up for the free intro course and found it
                      incredibly fun! I enrolled shortly thereafter. The next 12
                      weeks was the best - and most grueling - time of my life.
                      Since completing the course, I’ve successfully switched
                      careers, working as a Software Engineer at a VR startup. ”
                    </h1>
                  </div>
                </div>
                <div className="basis-[30%] bg-slate-500 rounded-lg p-5 drop-shadow-xl ">
                  <div className=" flex gap-2 flex-row items-center">
                    <Image
                      className="rounded-full"
                      src="/image-jonathan.jpg"
                      alt="img"
                      width={30}
                      height={30}
                    />

                    <div className="flex-col text-white ">
                      <h1 className="text-sm">Jonathan Walters</h1>
                      <p className="text-xs opacity-[50%]">Verified Graduate</p>
                    </div>
                  </div>
                  <div className="flex mt-2">
                    <h1 className="text-2xl font-bold text-white opacity-[80%]">
                      The team was very supportive and kept me motivated
                    </h1>
                  </div>
                  <div className="flex mt-2">
                    <h1 className="text-[13px] text-gray-300 opacity-[80%]">
                      “ I started as a total newbie with virtually no coding
                      skills. I now work as a mobile engineer for a big company.
                      This was one of the best investments I’ve made in myself.
                      ”
                    </h1>
                  </div>
                </div>
              </div>
              <div className="flex flex-col sm:flex-row gap-10 sm:gap-2 mt-10 sm:mt-2 ">
                <div className="basis-[30%] bg-white p-5 rounded-lg drop-shadow-xl">
                  <div className=" flex gap-2 flex-row items-center">
                    <Image
                      className="rounded-full"
                      src="/image-jeanette.jpg"
                      alt="img"
                      width={30}
                      height={30}
                    />

                    <div className="flex-col text-slate-600 ">
                      <h1 className="text-sm">Jeanette Harmon</h1>
                      <p className="text-xs opacity-[50%]">Verified Graduate</p>
                    </div>
                  </div>
                  <div className="flex mt-2">
                    <h1 className="text-2xl font-bold text-slate-600 opacity-[80%]">
                      An overall wonderful and rewarding experience
                    </h1>
                  </div>
                  <div className="flex mt-2">
                    <h1 className="text-[13px] text-slate-500 opacity-[80%]">
                      “ Thank you for the wonderful experience! I now have a job
                      I really enjoy, and make a good living while doing
                      something I love. ”
                    </h1>
                  </div>
                </div>
                <div className="basis-[70%] bg-gray-900 rounded-lg p-5 drop-shadow-xl">
                  <div className=" flex gap-2 flex-row items-center">
                    <Image
                      className="rounded-full"
                      src="/image-patrick.jpg"
                      alt="img"
                      width={30}
                      height={30}
                    />

                    <div className="flex-col text-white ">
                      <h1 className="text-sm">Patrick Abrams</h1>
                      <p className="text-xs opacity-[50%]">Verified Graduate</p>
                    </div>
                  </div>
                  <div className="flex mt-2">
                    <h1 className="text-2xl font-bold text-white opacity-[80%]">
                      Awesome teaching support from TAs who did the bootcamp
                      themselves. Getting guidance from them and learning from
                      their experiences was easy.
                    </h1>
                  </div>
                  <div className="flex mt-2">
                    <h1 className="text-[13px] text-gray-300 opacity-[80%]">
                      “ The staff seem genuinely concerned about my progress
                      which I find really refreshing. The program gave me the
                      confidence necessary to be able to go out in the world and
                      present myself as a capable junior developer. The standard
                      is above the rest. You will get the personal attention you
                      need from an incredible community of smart and amazing
                      people. ”
                    </h1>
                  </div>
                </div>
              </div>
            </div>
            <div className="basis-1/4 mb-20 ">
              <div className="bg-white rounded-lg p-5 drop-shadow-xl">
                <div className=" flex gap-2 flex-row items-center">
                  <Image
                    className="rounded-full"
                    src="/image-kira.jpg"
                    alt="img"
                    width={30}
                    height={30}
                  />

                  <div className="flex-col text-slate-600 ">
                    <h1 className="text-sm">Kira Whittle</h1>
                    <p className="text-xs opacity-[50%]">Verified Graduate</p>
                  </div>
                </div>
                <div className="flex mt-2">
                  <h1 className="text-xl font-bold text-slate-600 opacity-[80%]">
                    Such a life-changing experience. Highly recommended!
                  </h1>
                </div>
                <div className="flex mt-2 mb-9 ">
                  <h1 className="text-[13px] text-slate-500 opacity-[80%]  text-left">
                    “ Before joining the bootcamp, I’ve never written a line of
                    code. I needed some structure from professionals who can
                    help me learn programming step by step. I was encouraged to
                    enroll by a former student of theirs who can only say
                    wonderful things about the program. The entire curriculum
                    and staff did not disappoint. They were very hands-on and I
                    never had to wait long for assistance. The agile team
                    project, in particular, was outstanding. It took my learning
                    to the next level in a way that no tutorial could ever have.
                    In fact, I’ve often referred to it during interviews as an
                    example of my developent experience. It certainly helped me
                    land a job as a full-stack developer after receiving
                    multiple offers. 100% recommend! ”
                  </h1>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
